"""Forecaster entry point for one system (generated by gtlab.package from predict_template.py).

Loads model.json (+ optional model.npz) and gt_infer.py relative to this file, caches them in a
module global, and never keeps trajectory state between calls. Any failure falls back to
clipped persistence for that episode, so predict() never raises.
"""
import importlib.util
import math
from pathlib import Path

SYSTEM = "__SYSTEM__"
HARD = {}
_HERE = Path(__file__).resolve().parent
_CACHE = {}


def _load():
    if "doc" in _CACHE:
        return _CACHE["infer"], _CACHE["doc"]
    if _CACHE.get("failed"):
        raise RuntimeError("model failed to load")
    try:
        spec = importlib.util.spec_from_file_location(f"gt_{SYSTEM}_infer", str(_HERE / "gt_infer.py"))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        doc = mod.load_doc(_HERE)
    except Exception:
        _CACHE["failed"] = True
        raise
    _CACHE["infer"] = mod
    _CACHE["doc"] = doc
    return mod, doc


def _fnum(v):
    try:
        f = float(v)
    except (TypeError, ValueError):
        return 0.0
    return f if math.isfinite(f) else 0.0


def _persistence(initial, n, names):
    row = {}
    for k in names:
        v = _fnum(initial.get(k)) if isinstance(initial, dict) else 0.0
        lo, hi = HARD.get(k, (0.0, None))
        if lo is not None and v < lo:
            v = float(lo)
        if hi is not None and v > hi:
            v = float(hi)
        row[k] = v
    return [dict(row) for _ in range(n)]


def _names(initial, context):
    names = list(initial.keys()) if isinstance(initial, dict) else []
    try:
        for k in context.get("observables", []) or []:
            if k not in names:
                names.append(k)
    except Exception:
        pass
    return names


def _valid(out, n, names):
    if not isinstance(out, list) or len(out) != n:
        return False
    for row in out:
        if not isinstance(row, dict) or len(row) != len(names):
            return False
        for k in names:
            v = row.get(k)
            if not isinstance(v, float) or not math.isfinite(v):
                return False
    return True


def predict(initial, interventions, context):
    try:
        n = len(interventions)
    except Exception:
        n = 4000
    try:
        names = _names(initial, context)
    except Exception:
        names = []
    try:
        infer, doc = _load()
        init = {k: initial.get(k, 0.0) for k in names}
        out = infer.predict_episode(doc, init, interventions, context, base_dir=_HERE, tag=SYSTEM)
        if _valid(out, n, names):
            return out
    except Exception:
        pass
    return _persistence(initial, n, names)
